services:

  postgres:
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"

  service:
    build: https://github.com/izertis/identfy-entity-service.git
    ports:
      - "8001:8080"
    environment:
      - NODE_ENV=conformance # It can also be changed to "production" environment, which uses EBSI's pilot environment
      - BACKEND_URL=${PUBLIC_URL}
      # Default user for service. Change on production environment
      - BACKEND_USER=service
      - BACKEND_PASS=service

  backend:
    build: https://github.com/izertis/identfy-entity-backend.git
    environment:
      BACKEND_DOMAIN: ${PUBLIC_URL}
      ALLOWED_HOSTS: "*"
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
      VC_SERVICE_URL: http://service:8080/api
      # Example Issuer configuration. Change on production environment
      DID: ${DID}
      # Only for testing purpouse. Change on production environment
      DEVELOPER_MOCKUP_ENTITIES: True
      EBSI_DIDR_URL: "https://api-conformance.ebsi.eu/did-registry/v5/identifiers"
      EBSI_TIR_URL: "https://api-conformance.ebsi.eu/trusted-issuers-registry/v5/issuers"
      # Default value. Change on production environment
    ports:
      - 8000:8000
    healthcheck:
      test: wget --no-verbose --tries=1 --spider ${PUBLIC_URL}/swagger/
      interval: 5s
      timeout: 5s
      retries: 5
    depends_on:
      - postgres
      - service
